# .github/workflows/aggregate-metrics.yml
name: Aggregate Metrics

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Aggregate Metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/aggregate-metrics.js

      - name: Commit Updated Metrics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/metrics.json
          git commit -m "Update metrics" || exit 0
          git push